@startuml diagramaDeEstados



State Articulo{
    
    
    PostularArticulo --> RevisarArticulo : RevisarArticulo
    
    RevisarArticulo --> AprobarArticulo : AprobarArticulo
    
    RevisarArticulo --> RechazarArticulo : RechazarArticulo
    
    AprobarArticulo --> ArticuloPublicado : PublicarArticulo
    
    RechazarArticulo --> PostularArticulo : PostularArticulo
    
    ArticuloPublicado --> [*] : PublicarArticulo

}


@enduml
/'  
Postular articulo --> se asigna -->
--> comentarios --> aprobacion´

'/

